language: generic

services:
 - docker

before_install:
  - docker build -f client/Dockerfile.dev -t stefanflorea/react-test ./client

script:
  - docker run -e CI=true stefanflorea/react-test npm test

after_success:
  # build all production images
  - docker build -t stefanflorea/multicontainer-app-client ./client
  - docker build -t stefanflorea/multicontainer-app-server ./server
  - docker build -t stefanflorea/multicontainer-app-nginx ./nginx
  - docker build -t stefanflorea/multicontainer-app-worker ./worker

  # login to docker using secret credentials
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push built images to docker hub
  - docker push stefanflorea/multicontainer-app-client
  - docker push stefanflorea/multicontainer-app-server
  - docker push stefanflorea/multicontainer-app-nginx
  - docker push stefanflorea/multicontainer-app-worker
